# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api_pb2 as api__pb2


class VersionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Version = channel.unary_unary(
        '/walletrpc.VersionService/Version',
        request_serializer=api__pb2.VersionRequest.SerializeToString,
        response_deserializer=api__pb2.VersionResponse.FromString,
        )


class VersionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Version(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VersionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Version': grpc.unary_unary_rpc_method_handler(
          servicer.Version,
          request_deserializer=api__pb2.VersionRequest.FromString,
          response_serializer=api__pb2.VersionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.VersionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class WalletServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/walletrpc.WalletService/Ping',
        request_serializer=api__pb2.PingRequest.SerializeToString,
        response_deserializer=api__pb2.PingResponse.FromString,
        )
    self.Network = channel.unary_unary(
        '/walletrpc.WalletService/Network',
        request_serializer=api__pb2.NetworkRequest.SerializeToString,
        response_deserializer=api__pb2.NetworkResponse.FromString,
        )
    self.AccountNumber = channel.unary_unary(
        '/walletrpc.WalletService/AccountNumber',
        request_serializer=api__pb2.AccountNumberRequest.SerializeToString,
        response_deserializer=api__pb2.AccountNumberResponse.FromString,
        )
    self.Accounts = channel.unary_unary(
        '/walletrpc.WalletService/Accounts',
        request_serializer=api__pb2.AccountsRequest.SerializeToString,
        response_deserializer=api__pb2.AccountsResponse.FromString,
        )
    self.Balance = channel.unary_unary(
        '/walletrpc.WalletService/Balance',
        request_serializer=api__pb2.BalanceRequest.SerializeToString,
        response_deserializer=api__pb2.BalanceResponse.FromString,
        )
    self.GetAccountExtendedPubKey = channel.unary_unary(
        '/walletrpc.WalletService/GetAccountExtendedPubKey',
        request_serializer=api__pb2.GetAccountExtendedPubKeyRequest.SerializeToString,
        response_deserializer=api__pb2.GetAccountExtendedPubKeyResponse.FromString,
        )
    self.GetTransaction = channel.unary_unary(
        '/walletrpc.WalletService/GetTransaction',
        request_serializer=api__pb2.GetTransactionRequest.SerializeToString,
        response_deserializer=api__pb2.GetTransactionResponse.FromString,
        )
    self.GetTransactions = channel.unary_stream(
        '/walletrpc.WalletService/GetTransactions',
        request_serializer=api__pb2.GetTransactionsRequest.SerializeToString,
        response_deserializer=api__pb2.GetTransactionsResponse.FromString,
        )
    self.GetTickets = channel.unary_stream(
        '/walletrpc.WalletService/GetTickets',
        request_serializer=api__pb2.GetTicketsRequest.SerializeToString,
        response_deserializer=api__pb2.GetTicketsResponse.FromString,
        )
    self.TicketPrice = channel.unary_unary(
        '/walletrpc.WalletService/TicketPrice',
        request_serializer=api__pb2.TicketPriceRequest.SerializeToString,
        response_deserializer=api__pb2.TicketPriceResponse.FromString,
        )
    self.StakeInfo = channel.unary_unary(
        '/walletrpc.WalletService/StakeInfo',
        request_serializer=api__pb2.StakeInfoRequest.SerializeToString,
        response_deserializer=api__pb2.StakeInfoResponse.FromString,
        )
    self.BlockInfo = channel.unary_unary(
        '/walletrpc.WalletService/BlockInfo',
        request_serializer=api__pb2.BlockInfoRequest.SerializeToString,
        response_deserializer=api__pb2.BlockInfoResponse.FromString,
        )
    self.BestBlock = channel.unary_unary(
        '/walletrpc.WalletService/BestBlock',
        request_serializer=api__pb2.BestBlockRequest.SerializeToString,
        response_deserializer=api__pb2.BestBlockResponse.FromString,
        )
    self.TransactionNotifications = channel.unary_stream(
        '/walletrpc.WalletService/TransactionNotifications',
        request_serializer=api__pb2.TransactionNotificationsRequest.SerializeToString,
        response_deserializer=api__pb2.TransactionNotificationsResponse.FromString,
        )
    self.AccountNotifications = channel.unary_stream(
        '/walletrpc.WalletService/AccountNotifications',
        request_serializer=api__pb2.AccountNotificationsRequest.SerializeToString,
        response_deserializer=api__pb2.AccountNotificationsResponse.FromString,
        )
    self.ConfirmationNotifications = channel.stream_stream(
        '/walletrpc.WalletService/ConfirmationNotifications',
        request_serializer=api__pb2.ConfirmationNotificationsRequest.SerializeToString,
        response_deserializer=api__pb2.ConfirmationNotificationsResponse.FromString,
        )
    self.ChangePassphrase = channel.unary_unary(
        '/walletrpc.WalletService/ChangePassphrase',
        request_serializer=api__pb2.ChangePassphraseRequest.SerializeToString,
        response_deserializer=api__pb2.ChangePassphraseResponse.FromString,
        )
    self.RenameAccount = channel.unary_unary(
        '/walletrpc.WalletService/RenameAccount',
        request_serializer=api__pb2.RenameAccountRequest.SerializeToString,
        response_deserializer=api__pb2.RenameAccountResponse.FromString,
        )
    self.Rescan = channel.unary_stream(
        '/walletrpc.WalletService/Rescan',
        request_serializer=api__pb2.RescanRequest.SerializeToString,
        response_deserializer=api__pb2.RescanResponse.FromString,
        )
    self.NextAccount = channel.unary_unary(
        '/walletrpc.WalletService/NextAccount',
        request_serializer=api__pb2.NextAccountRequest.SerializeToString,
        response_deserializer=api__pb2.NextAccountResponse.FromString,
        )
    self.NextAddress = channel.unary_unary(
        '/walletrpc.WalletService/NextAddress',
        request_serializer=api__pb2.NextAddressRequest.SerializeToString,
        response_deserializer=api__pb2.NextAddressResponse.FromString,
        )
    self.ImportPrivateKey = channel.unary_unary(
        '/walletrpc.WalletService/ImportPrivateKey',
        request_serializer=api__pb2.ImportPrivateKeyRequest.SerializeToString,
        response_deserializer=api__pb2.ImportPrivateKeyResponse.FromString,
        )
    self.ImportScript = channel.unary_unary(
        '/walletrpc.WalletService/ImportScript',
        request_serializer=api__pb2.ImportScriptRequest.SerializeToString,
        response_deserializer=api__pb2.ImportScriptResponse.FromString,
        )
    self.FundTransaction = channel.unary_unary(
        '/walletrpc.WalletService/FundTransaction',
        request_serializer=api__pb2.FundTransactionRequest.SerializeToString,
        response_deserializer=api__pb2.FundTransactionResponse.FromString,
        )
    self.UnspentOutputs = channel.unary_stream(
        '/walletrpc.WalletService/UnspentOutputs',
        request_serializer=api__pb2.UnspentOutputsRequest.SerializeToString,
        response_deserializer=api__pb2.UnspentOutputResponse.FromString,
        )
    self.ConstructTransaction = channel.unary_unary(
        '/walletrpc.WalletService/ConstructTransaction',
        request_serializer=api__pb2.ConstructTransactionRequest.SerializeToString,
        response_deserializer=api__pb2.ConstructTransactionResponse.FromString,
        )
    self.SignTransaction = channel.unary_unary(
        '/walletrpc.WalletService/SignTransaction',
        request_serializer=api__pb2.SignTransactionRequest.SerializeToString,
        response_deserializer=api__pb2.SignTransactionResponse.FromString,
        )
    self.SignTransactions = channel.unary_unary(
        '/walletrpc.WalletService/SignTransactions',
        request_serializer=api__pb2.SignTransactionsRequest.SerializeToString,
        response_deserializer=api__pb2.SignTransactionsResponse.FromString,
        )
    self.CreateSignature = channel.unary_unary(
        '/walletrpc.WalletService/CreateSignature',
        request_serializer=api__pb2.CreateSignatureRequest.SerializeToString,
        response_deserializer=api__pb2.CreateSignatureResponse.FromString,
        )
    self.PublishTransaction = channel.unary_unary(
        '/walletrpc.WalletService/PublishTransaction',
        request_serializer=api__pb2.PublishTransactionRequest.SerializeToString,
        response_deserializer=api__pb2.PublishTransactionResponse.FromString,
        )
    self.PublishUnminedTransactions = channel.unary_unary(
        '/walletrpc.WalletService/PublishUnminedTransactions',
        request_serializer=api__pb2.PublishUnminedTransactionsRequest.SerializeToString,
        response_deserializer=api__pb2.PublishUnminedTransactionsResponse.FromString,
        )
    self.PurchaseTickets = channel.unary_unary(
        '/walletrpc.WalletService/PurchaseTickets',
        request_serializer=api__pb2.PurchaseTicketsRequest.SerializeToString,
        response_deserializer=api__pb2.PurchaseTicketsResponse.FromString,
        )
    self.RevokeTickets = channel.unary_unary(
        '/walletrpc.WalletService/RevokeTickets',
        request_serializer=api__pb2.RevokeTicketsRequest.SerializeToString,
        response_deserializer=api__pb2.RevokeTicketsResponse.FromString,
        )
    self.LoadActiveDataFilters = channel.unary_unary(
        '/walletrpc.WalletService/LoadActiveDataFilters',
        request_serializer=api__pb2.LoadActiveDataFiltersRequest.SerializeToString,
        response_deserializer=api__pb2.LoadActiveDataFiltersResponse.FromString,
        )
    self.SignMessage = channel.unary_unary(
        '/walletrpc.WalletService/SignMessage',
        request_serializer=api__pb2.SignMessageRequest.SerializeToString,
        response_deserializer=api__pb2.SignMessageResponse.FromString,
        )
    self.SignMessages = channel.unary_unary(
        '/walletrpc.WalletService/SignMessages',
        request_serializer=api__pb2.SignMessagesRequest.SerializeToString,
        response_deserializer=api__pb2.SignMessagesResponse.FromString,
        )
    self.ValidateAddress = channel.unary_unary(
        '/walletrpc.WalletService/ValidateAddress',
        request_serializer=api__pb2.ValidateAddressRequest.SerializeToString,
        response_deserializer=api__pb2.ValidateAddressResponse.FromString,
        )
    self.CommittedTickets = channel.unary_unary(
        '/walletrpc.WalletService/CommittedTickets',
        request_serializer=api__pb2.CommittedTicketsRequest.SerializeToString,
        response_deserializer=api__pb2.CommittedTicketsResponse.FromString,
        )


class WalletServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    """Queries
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Network(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AccountNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Accounts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Balance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountExtendedPubKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTickets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TicketPrice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StakeInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlockInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BestBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransactionNotifications(self, request, context):
    """Notifications
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AccountNotifications(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfirmationNotifications(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangePassphrase(self, request, context):
    """Control
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RenameAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Rescan(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NextAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NextAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportPrivateKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportScript(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FundTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnspentOutputs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConstructTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSignature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PublishTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PublishUnminedTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PurchaseTickets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RevokeTickets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadActiveDataFilters(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CommittedTickets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=api__pb2.PingRequest.FromString,
          response_serializer=api__pb2.PingResponse.SerializeToString,
      ),
      'Network': grpc.unary_unary_rpc_method_handler(
          servicer.Network,
          request_deserializer=api__pb2.NetworkRequest.FromString,
          response_serializer=api__pb2.NetworkResponse.SerializeToString,
      ),
      'AccountNumber': grpc.unary_unary_rpc_method_handler(
          servicer.AccountNumber,
          request_deserializer=api__pb2.AccountNumberRequest.FromString,
          response_serializer=api__pb2.AccountNumberResponse.SerializeToString,
      ),
      'Accounts': grpc.unary_unary_rpc_method_handler(
          servicer.Accounts,
          request_deserializer=api__pb2.AccountsRequest.FromString,
          response_serializer=api__pb2.AccountsResponse.SerializeToString,
      ),
      'Balance': grpc.unary_unary_rpc_method_handler(
          servicer.Balance,
          request_deserializer=api__pb2.BalanceRequest.FromString,
          response_serializer=api__pb2.BalanceResponse.SerializeToString,
      ),
      'GetAccountExtendedPubKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountExtendedPubKey,
          request_deserializer=api__pb2.GetAccountExtendedPubKeyRequest.FromString,
          response_serializer=api__pb2.GetAccountExtendedPubKeyResponse.SerializeToString,
      ),
      'GetTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransaction,
          request_deserializer=api__pb2.GetTransactionRequest.FromString,
          response_serializer=api__pb2.GetTransactionResponse.SerializeToString,
      ),
      'GetTransactions': grpc.unary_stream_rpc_method_handler(
          servicer.GetTransactions,
          request_deserializer=api__pb2.GetTransactionsRequest.FromString,
          response_serializer=api__pb2.GetTransactionsResponse.SerializeToString,
      ),
      'GetTickets': grpc.unary_stream_rpc_method_handler(
          servicer.GetTickets,
          request_deserializer=api__pb2.GetTicketsRequest.FromString,
          response_serializer=api__pb2.GetTicketsResponse.SerializeToString,
      ),
      'TicketPrice': grpc.unary_unary_rpc_method_handler(
          servicer.TicketPrice,
          request_deserializer=api__pb2.TicketPriceRequest.FromString,
          response_serializer=api__pb2.TicketPriceResponse.SerializeToString,
      ),
      'StakeInfo': grpc.unary_unary_rpc_method_handler(
          servicer.StakeInfo,
          request_deserializer=api__pb2.StakeInfoRequest.FromString,
          response_serializer=api__pb2.StakeInfoResponse.SerializeToString,
      ),
      'BlockInfo': grpc.unary_unary_rpc_method_handler(
          servicer.BlockInfo,
          request_deserializer=api__pb2.BlockInfoRequest.FromString,
          response_serializer=api__pb2.BlockInfoResponse.SerializeToString,
      ),
      'BestBlock': grpc.unary_unary_rpc_method_handler(
          servicer.BestBlock,
          request_deserializer=api__pb2.BestBlockRequest.FromString,
          response_serializer=api__pb2.BestBlockResponse.SerializeToString,
      ),
      'TransactionNotifications': grpc.unary_stream_rpc_method_handler(
          servicer.TransactionNotifications,
          request_deserializer=api__pb2.TransactionNotificationsRequest.FromString,
          response_serializer=api__pb2.TransactionNotificationsResponse.SerializeToString,
      ),
      'AccountNotifications': grpc.unary_stream_rpc_method_handler(
          servicer.AccountNotifications,
          request_deserializer=api__pb2.AccountNotificationsRequest.FromString,
          response_serializer=api__pb2.AccountNotificationsResponse.SerializeToString,
      ),
      'ConfirmationNotifications': grpc.stream_stream_rpc_method_handler(
          servicer.ConfirmationNotifications,
          request_deserializer=api__pb2.ConfirmationNotificationsRequest.FromString,
          response_serializer=api__pb2.ConfirmationNotificationsResponse.SerializeToString,
      ),
      'ChangePassphrase': grpc.unary_unary_rpc_method_handler(
          servicer.ChangePassphrase,
          request_deserializer=api__pb2.ChangePassphraseRequest.FromString,
          response_serializer=api__pb2.ChangePassphraseResponse.SerializeToString,
      ),
      'RenameAccount': grpc.unary_unary_rpc_method_handler(
          servicer.RenameAccount,
          request_deserializer=api__pb2.RenameAccountRequest.FromString,
          response_serializer=api__pb2.RenameAccountResponse.SerializeToString,
      ),
      'Rescan': grpc.unary_stream_rpc_method_handler(
          servicer.Rescan,
          request_deserializer=api__pb2.RescanRequest.FromString,
          response_serializer=api__pb2.RescanResponse.SerializeToString,
      ),
      'NextAccount': grpc.unary_unary_rpc_method_handler(
          servicer.NextAccount,
          request_deserializer=api__pb2.NextAccountRequest.FromString,
          response_serializer=api__pb2.NextAccountResponse.SerializeToString,
      ),
      'NextAddress': grpc.unary_unary_rpc_method_handler(
          servicer.NextAddress,
          request_deserializer=api__pb2.NextAddressRequest.FromString,
          response_serializer=api__pb2.NextAddressResponse.SerializeToString,
      ),
      'ImportPrivateKey': grpc.unary_unary_rpc_method_handler(
          servicer.ImportPrivateKey,
          request_deserializer=api__pb2.ImportPrivateKeyRequest.FromString,
          response_serializer=api__pb2.ImportPrivateKeyResponse.SerializeToString,
      ),
      'ImportScript': grpc.unary_unary_rpc_method_handler(
          servicer.ImportScript,
          request_deserializer=api__pb2.ImportScriptRequest.FromString,
          response_serializer=api__pb2.ImportScriptResponse.SerializeToString,
      ),
      'FundTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.FundTransaction,
          request_deserializer=api__pb2.FundTransactionRequest.FromString,
          response_serializer=api__pb2.FundTransactionResponse.SerializeToString,
      ),
      'UnspentOutputs': grpc.unary_stream_rpc_method_handler(
          servicer.UnspentOutputs,
          request_deserializer=api__pb2.UnspentOutputsRequest.FromString,
          response_serializer=api__pb2.UnspentOutputResponse.SerializeToString,
      ),
      'ConstructTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.ConstructTransaction,
          request_deserializer=api__pb2.ConstructTransactionRequest.FromString,
          response_serializer=api__pb2.ConstructTransactionResponse.SerializeToString,
      ),
      'SignTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.SignTransaction,
          request_deserializer=api__pb2.SignTransactionRequest.FromString,
          response_serializer=api__pb2.SignTransactionResponse.SerializeToString,
      ),
      'SignTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.SignTransactions,
          request_deserializer=api__pb2.SignTransactionsRequest.FromString,
          response_serializer=api__pb2.SignTransactionsResponse.SerializeToString,
      ),
      'CreateSignature': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSignature,
          request_deserializer=api__pb2.CreateSignatureRequest.FromString,
          response_serializer=api__pb2.CreateSignatureResponse.SerializeToString,
      ),
      'PublishTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.PublishTransaction,
          request_deserializer=api__pb2.PublishTransactionRequest.FromString,
          response_serializer=api__pb2.PublishTransactionResponse.SerializeToString,
      ),
      'PublishUnminedTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.PublishUnminedTransactions,
          request_deserializer=api__pb2.PublishUnminedTransactionsRequest.FromString,
          response_serializer=api__pb2.PublishUnminedTransactionsResponse.SerializeToString,
      ),
      'PurchaseTickets': grpc.unary_unary_rpc_method_handler(
          servicer.PurchaseTickets,
          request_deserializer=api__pb2.PurchaseTicketsRequest.FromString,
          response_serializer=api__pb2.PurchaseTicketsResponse.SerializeToString,
      ),
      'RevokeTickets': grpc.unary_unary_rpc_method_handler(
          servicer.RevokeTickets,
          request_deserializer=api__pb2.RevokeTicketsRequest.FromString,
          response_serializer=api__pb2.RevokeTicketsResponse.SerializeToString,
      ),
      'LoadActiveDataFilters': grpc.unary_unary_rpc_method_handler(
          servicer.LoadActiveDataFilters,
          request_deserializer=api__pb2.LoadActiveDataFiltersRequest.FromString,
          response_serializer=api__pb2.LoadActiveDataFiltersResponse.SerializeToString,
      ),
      'SignMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SignMessage,
          request_deserializer=api__pb2.SignMessageRequest.FromString,
          response_serializer=api__pb2.SignMessageResponse.SerializeToString,
      ),
      'SignMessages': grpc.unary_unary_rpc_method_handler(
          servicer.SignMessages,
          request_deserializer=api__pb2.SignMessagesRequest.FromString,
          response_serializer=api__pb2.SignMessagesResponse.SerializeToString,
      ),
      'ValidateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateAddress,
          request_deserializer=api__pb2.ValidateAddressRequest.FromString,
          response_serializer=api__pb2.ValidateAddressResponse.SerializeToString,
      ),
      'CommittedTickets': grpc.unary_unary_rpc_method_handler(
          servicer.CommittedTickets,
          request_deserializer=api__pb2.CommittedTicketsRequest.FromString,
          response_serializer=api__pb2.CommittedTicketsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.WalletService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class WalletLoaderServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.WalletExists = channel.unary_unary(
        '/walletrpc.WalletLoaderService/WalletExists',
        request_serializer=api__pb2.WalletExistsRequest.SerializeToString,
        response_deserializer=api__pb2.WalletExistsResponse.FromString,
        )
    self.CreateWallet = channel.unary_unary(
        '/walletrpc.WalletLoaderService/CreateWallet',
        request_serializer=api__pb2.CreateWalletRequest.SerializeToString,
        response_deserializer=api__pb2.CreateWalletResponse.FromString,
        )
    self.CreateWatchingOnlyWallet = channel.unary_unary(
        '/walletrpc.WalletLoaderService/CreateWatchingOnlyWallet',
        request_serializer=api__pb2.CreateWatchingOnlyWalletRequest.SerializeToString,
        response_deserializer=api__pb2.CreateWatchingOnlyWalletResponse.FromString,
        )
    self.OpenWallet = channel.unary_unary(
        '/walletrpc.WalletLoaderService/OpenWallet',
        request_serializer=api__pb2.OpenWalletRequest.SerializeToString,
        response_deserializer=api__pb2.OpenWalletResponse.FromString,
        )
    self.CloseWallet = channel.unary_unary(
        '/walletrpc.WalletLoaderService/CloseWallet',
        request_serializer=api__pb2.CloseWalletRequest.SerializeToString,
        response_deserializer=api__pb2.CloseWalletResponse.FromString,
        )
    self.StartConsensusRpc = channel.unary_unary(
        '/walletrpc.WalletLoaderService/StartConsensusRpc',
        request_serializer=api__pb2.StartConsensusRpcRequest.SerializeToString,
        response_deserializer=api__pb2.StartConsensusRpcResponse.FromString,
        )
    self.DiscoverAddresses = channel.unary_unary(
        '/walletrpc.WalletLoaderService/DiscoverAddresses',
        request_serializer=api__pb2.DiscoverAddressesRequest.SerializeToString,
        response_deserializer=api__pb2.DiscoverAddressesResponse.FromString,
        )
    self.SubscribeToBlockNotifications = channel.unary_unary(
        '/walletrpc.WalletLoaderService/SubscribeToBlockNotifications',
        request_serializer=api__pb2.SubscribeToBlockNotificationsRequest.SerializeToString,
        response_deserializer=api__pb2.SubscribeToBlockNotificationsResponse.FromString,
        )
    self.FetchHeaders = channel.unary_unary(
        '/walletrpc.WalletLoaderService/FetchHeaders',
        request_serializer=api__pb2.FetchHeadersRequest.SerializeToString,
        response_deserializer=api__pb2.FetchHeadersResponse.FromString,
        )
    self.FetchMissingCFilters = channel.unary_unary(
        '/walletrpc.WalletLoaderService/FetchMissingCFilters',
        request_serializer=api__pb2.FetchMissingCFiltersRequest.SerializeToString,
        response_deserializer=api__pb2.FetchMissingCFiltersResponse.FromString,
        )
    self.SpvSync = channel.unary_stream(
        '/walletrpc.WalletLoaderService/SpvSync',
        request_serializer=api__pb2.SpvSyncRequest.SerializeToString,
        response_deserializer=api__pb2.SpvSyncResponse.FromString,
        )
    self.RescanPoint = channel.unary_unary(
        '/walletrpc.WalletLoaderService/RescanPoint',
        request_serializer=api__pb2.RescanPointRequest.SerializeToString,
        response_deserializer=api__pb2.RescanPointResponse.FromString,
        )


class WalletLoaderServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def WalletExists(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateWatchingOnlyWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartConsensusRpc(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DiscoverAddresses(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeToBlockNotifications(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchHeaders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchMissingCFilters(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SpvSync(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RescanPoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WalletLoaderServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'WalletExists': grpc.unary_unary_rpc_method_handler(
          servicer.WalletExists,
          request_deserializer=api__pb2.WalletExistsRequest.FromString,
          response_serializer=api__pb2.WalletExistsResponse.SerializeToString,
      ),
      'CreateWallet': grpc.unary_unary_rpc_method_handler(
          servicer.CreateWallet,
          request_deserializer=api__pb2.CreateWalletRequest.FromString,
          response_serializer=api__pb2.CreateWalletResponse.SerializeToString,
      ),
      'CreateWatchingOnlyWallet': grpc.unary_unary_rpc_method_handler(
          servicer.CreateWatchingOnlyWallet,
          request_deserializer=api__pb2.CreateWatchingOnlyWalletRequest.FromString,
          response_serializer=api__pb2.CreateWatchingOnlyWalletResponse.SerializeToString,
      ),
      'OpenWallet': grpc.unary_unary_rpc_method_handler(
          servicer.OpenWallet,
          request_deserializer=api__pb2.OpenWalletRequest.FromString,
          response_serializer=api__pb2.OpenWalletResponse.SerializeToString,
      ),
      'CloseWallet': grpc.unary_unary_rpc_method_handler(
          servicer.CloseWallet,
          request_deserializer=api__pb2.CloseWalletRequest.FromString,
          response_serializer=api__pb2.CloseWalletResponse.SerializeToString,
      ),
      'StartConsensusRpc': grpc.unary_unary_rpc_method_handler(
          servicer.StartConsensusRpc,
          request_deserializer=api__pb2.StartConsensusRpcRequest.FromString,
          response_serializer=api__pb2.StartConsensusRpcResponse.SerializeToString,
      ),
      'DiscoverAddresses': grpc.unary_unary_rpc_method_handler(
          servicer.DiscoverAddresses,
          request_deserializer=api__pb2.DiscoverAddressesRequest.FromString,
          response_serializer=api__pb2.DiscoverAddressesResponse.SerializeToString,
      ),
      'SubscribeToBlockNotifications': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeToBlockNotifications,
          request_deserializer=api__pb2.SubscribeToBlockNotificationsRequest.FromString,
          response_serializer=api__pb2.SubscribeToBlockNotificationsResponse.SerializeToString,
      ),
      'FetchHeaders': grpc.unary_unary_rpc_method_handler(
          servicer.FetchHeaders,
          request_deserializer=api__pb2.FetchHeadersRequest.FromString,
          response_serializer=api__pb2.FetchHeadersResponse.SerializeToString,
      ),
      'FetchMissingCFilters': grpc.unary_unary_rpc_method_handler(
          servicer.FetchMissingCFilters,
          request_deserializer=api__pb2.FetchMissingCFiltersRequest.FromString,
          response_serializer=api__pb2.FetchMissingCFiltersResponse.SerializeToString,
      ),
      'SpvSync': grpc.unary_stream_rpc_method_handler(
          servicer.SpvSync,
          request_deserializer=api__pb2.SpvSyncRequest.FromString,
          response_serializer=api__pb2.SpvSyncResponse.SerializeToString,
      ),
      'RescanPoint': grpc.unary_unary_rpc_method_handler(
          servicer.RescanPoint,
          request_deserializer=api__pb2.RescanPointRequest.FromString,
          response_serializer=api__pb2.RescanPointResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.WalletLoaderService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class TicketBuyerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartAutoBuyer = channel.unary_unary(
        '/walletrpc.TicketBuyerService/StartAutoBuyer',
        request_serializer=api__pb2.StartAutoBuyerRequest.SerializeToString,
        response_deserializer=api__pb2.StartAutoBuyerResponse.FromString,
        )
    self.StopAutoBuyer = channel.unary_unary(
        '/walletrpc.TicketBuyerService/StopAutoBuyer',
        request_serializer=api__pb2.StopAutoBuyerRequest.SerializeToString,
        response_deserializer=api__pb2.StopAutoBuyerResponse.FromString,
        )
    self.TicketBuyerConfig = channel.unary_unary(
        '/walletrpc.TicketBuyerService/TicketBuyerConfig',
        request_serializer=api__pb2.TicketBuyerConfigRequest.SerializeToString,
        response_deserializer=api__pb2.TicketBuyerConfigResponse.FromString,
        )
    self.SetAccount = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetAccount',
        request_serializer=api__pb2.SetAccountRequest.SerializeToString,
        response_deserializer=api__pb2.SetAccountResponse.FromString,
        )
    self.SetBalanceToMaintain = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetBalanceToMaintain',
        request_serializer=api__pb2.SetBalanceToMaintainRequest.SerializeToString,
        response_deserializer=api__pb2.SetBalanceToMaintainResponse.FromString,
        )
    self.SetMaxFee = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetMaxFee',
        request_serializer=api__pb2.SetMaxFeeRequest.SerializeToString,
        response_deserializer=api__pb2.SetMaxFeeResponse.FromString,
        )
    self.SetMaxPriceRelative = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetMaxPriceRelative',
        request_serializer=api__pb2.SetMaxPriceRelativeRequest.SerializeToString,
        response_deserializer=api__pb2.SetMaxPriceRelativeResponse.FromString,
        )
    self.SetMaxPriceAbsolute = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetMaxPriceAbsolute',
        request_serializer=api__pb2.SetMaxPriceAbsoluteRequest.SerializeToString,
        response_deserializer=api__pb2.SetMaxPriceAbsoluteResponse.FromString,
        )
    self.SetVotingAddress = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetVotingAddress',
        request_serializer=api__pb2.SetVotingAddressRequest.SerializeToString,
        response_deserializer=api__pb2.SetVotingAddressResponse.FromString,
        )
    self.SetPoolAddress = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetPoolAddress',
        request_serializer=api__pb2.SetPoolAddressRequest.SerializeToString,
        response_deserializer=api__pb2.SetPoolAddressResponse.FromString,
        )
    self.SetPoolFees = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetPoolFees',
        request_serializer=api__pb2.SetPoolFeesRequest.SerializeToString,
        response_deserializer=api__pb2.SetPoolFeesResponse.FromString,
        )
    self.SetMaxPerBlock = channel.unary_unary(
        '/walletrpc.TicketBuyerService/SetMaxPerBlock',
        request_serializer=api__pb2.SetMaxPerBlockRequest.SerializeToString,
        response_deserializer=api__pb2.SetMaxPerBlockResponse.FromString,
        )


class TicketBuyerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartAutoBuyer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopAutoBuyer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TicketBuyerConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetBalanceToMaintain(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMaxFee(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMaxPriceRelative(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMaxPriceAbsolute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetVotingAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPoolAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPoolFees(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMaxPerBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TicketBuyerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartAutoBuyer': grpc.unary_unary_rpc_method_handler(
          servicer.StartAutoBuyer,
          request_deserializer=api__pb2.StartAutoBuyerRequest.FromString,
          response_serializer=api__pb2.StartAutoBuyerResponse.SerializeToString,
      ),
      'StopAutoBuyer': grpc.unary_unary_rpc_method_handler(
          servicer.StopAutoBuyer,
          request_deserializer=api__pb2.StopAutoBuyerRequest.FromString,
          response_serializer=api__pb2.StopAutoBuyerResponse.SerializeToString,
      ),
      'TicketBuyerConfig': grpc.unary_unary_rpc_method_handler(
          servicer.TicketBuyerConfig,
          request_deserializer=api__pb2.TicketBuyerConfigRequest.FromString,
          response_serializer=api__pb2.TicketBuyerConfigResponse.SerializeToString,
      ),
      'SetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.SetAccount,
          request_deserializer=api__pb2.SetAccountRequest.FromString,
          response_serializer=api__pb2.SetAccountResponse.SerializeToString,
      ),
      'SetBalanceToMaintain': grpc.unary_unary_rpc_method_handler(
          servicer.SetBalanceToMaintain,
          request_deserializer=api__pb2.SetBalanceToMaintainRequest.FromString,
          response_serializer=api__pb2.SetBalanceToMaintainResponse.SerializeToString,
      ),
      'SetMaxFee': grpc.unary_unary_rpc_method_handler(
          servicer.SetMaxFee,
          request_deserializer=api__pb2.SetMaxFeeRequest.FromString,
          response_serializer=api__pb2.SetMaxFeeResponse.SerializeToString,
      ),
      'SetMaxPriceRelative': grpc.unary_unary_rpc_method_handler(
          servicer.SetMaxPriceRelative,
          request_deserializer=api__pb2.SetMaxPriceRelativeRequest.FromString,
          response_serializer=api__pb2.SetMaxPriceRelativeResponse.SerializeToString,
      ),
      'SetMaxPriceAbsolute': grpc.unary_unary_rpc_method_handler(
          servicer.SetMaxPriceAbsolute,
          request_deserializer=api__pb2.SetMaxPriceAbsoluteRequest.FromString,
          response_serializer=api__pb2.SetMaxPriceAbsoluteResponse.SerializeToString,
      ),
      'SetVotingAddress': grpc.unary_unary_rpc_method_handler(
          servicer.SetVotingAddress,
          request_deserializer=api__pb2.SetVotingAddressRequest.FromString,
          response_serializer=api__pb2.SetVotingAddressResponse.SerializeToString,
      ),
      'SetPoolAddress': grpc.unary_unary_rpc_method_handler(
          servicer.SetPoolAddress,
          request_deserializer=api__pb2.SetPoolAddressRequest.FromString,
          response_serializer=api__pb2.SetPoolAddressResponse.SerializeToString,
      ),
      'SetPoolFees': grpc.unary_unary_rpc_method_handler(
          servicer.SetPoolFees,
          request_deserializer=api__pb2.SetPoolFeesRequest.FromString,
          response_serializer=api__pb2.SetPoolFeesResponse.SerializeToString,
      ),
      'SetMaxPerBlock': grpc.unary_unary_rpc_method_handler(
          servicer.SetMaxPerBlock,
          request_deserializer=api__pb2.SetMaxPerBlockRequest.FromString,
          response_serializer=api__pb2.SetMaxPerBlockResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.TicketBuyerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SeedServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateRandomSeed = channel.unary_unary(
        '/walletrpc.SeedService/GenerateRandomSeed',
        request_serializer=api__pb2.GenerateRandomSeedRequest.SerializeToString,
        response_deserializer=api__pb2.GenerateRandomSeedResponse.FromString,
        )
    self.DecodeSeed = channel.unary_unary(
        '/walletrpc.SeedService/DecodeSeed',
        request_serializer=api__pb2.DecodeSeedRequest.SerializeToString,
        response_deserializer=api__pb2.DecodeSeedResponse.FromString,
        )


class SeedServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GenerateRandomSeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DecodeSeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SeedServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateRandomSeed': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateRandomSeed,
          request_deserializer=api__pb2.GenerateRandomSeedRequest.FromString,
          response_serializer=api__pb2.GenerateRandomSeedResponse.SerializeToString,
      ),
      'DecodeSeed': grpc.unary_unary_rpc_method_handler(
          servicer.DecodeSeed,
          request_deserializer=api__pb2.DecodeSeedRequest.FromString,
          response_serializer=api__pb2.DecodeSeedResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.SeedService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AgendaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Agendas = channel.unary_unary(
        '/walletrpc.AgendaService/Agendas',
        request_serializer=api__pb2.AgendasRequest.SerializeToString,
        response_deserializer=api__pb2.AgendasResponse.FromString,
        )


class AgendaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Agendas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgendaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Agendas': grpc.unary_unary_rpc_method_handler(
          servicer.Agendas,
          request_deserializer=api__pb2.AgendasRequest.FromString,
          response_serializer=api__pb2.AgendasResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.AgendaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class VotingServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.VoteChoices = channel.unary_unary(
        '/walletrpc.VotingService/VoteChoices',
        request_serializer=api__pb2.VoteChoicesRequest.SerializeToString,
        response_deserializer=api__pb2.VoteChoicesResponse.FromString,
        )
    self.SetVoteChoices = channel.unary_unary(
        '/walletrpc.VotingService/SetVoteChoices',
        request_serializer=api__pb2.SetVoteChoicesRequest.SerializeToString,
        response_deserializer=api__pb2.SetVoteChoicesResponse.FromString,
        )


class VotingServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def VoteChoices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetVoteChoices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VotingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'VoteChoices': grpc.unary_unary_rpc_method_handler(
          servicer.VoteChoices,
          request_deserializer=api__pb2.VoteChoicesRequest.FromString,
          response_serializer=api__pb2.VoteChoicesResponse.SerializeToString,
      ),
      'SetVoteChoices': grpc.unary_unary_rpc_method_handler(
          servicer.SetVoteChoices,
          request_deserializer=api__pb2.SetVoteChoicesRequest.FromString,
          response_serializer=api__pb2.SetVoteChoicesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.VotingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class MessageVerificationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.VerifyMessage = channel.unary_unary(
        '/walletrpc.MessageVerificationService/VerifyMessage',
        request_serializer=api__pb2.VerifyMessageRequest.SerializeToString,
        response_deserializer=api__pb2.VerifyMessageResponse.FromString,
        )


class MessageVerificationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def VerifyMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageVerificationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'VerifyMessage': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyMessage,
          request_deserializer=api__pb2.VerifyMessageRequest.FromString,
          response_serializer=api__pb2.VerifyMessageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.MessageVerificationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DecodeMessageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DecodeRawTransaction = channel.unary_unary(
        '/walletrpc.DecodeMessageService/DecodeRawTransaction',
        request_serializer=api__pb2.DecodeRawTransactionRequest.SerializeToString,
        response_deserializer=api__pb2.DecodeRawTransactionResponse.FromString,
        )


class DecodeMessageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DecodeRawTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DecodeMessageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DecodeRawTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.DecodeRawTransaction,
          request_deserializer=api__pb2.DecodeRawTransactionRequest.FromString,
          response_serializer=api__pb2.DecodeRawTransactionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'walletrpc.DecodeMessageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
